title: Aditya Bajaj
description: >
  ğŸ’» Full-Stack Developer  
  â˜ï¸ Cloud | ğŸ” Secure Auth | ğŸš€ DevOps  
  ğŸ¯ Clean Code | Scalable Systems
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
